"""

"""
import os 

from smug import version, log, WD, TIMESTAMP
from smug.handler import Handler

#!/usr/bin/env python

import click

@click.command()
@click.version_option(version)
@click.argument('folder', type=click.Path(exists=True))
@click.option("--meta", type=click.Path(exists=True), default="/", help="Override the autogenerated metadata with your own")
@click.option("--dry", is_flag=True, default=False, help="Does not execute anything")
@click.option("--parentfolder", is_flag=True, default=False, help="Samples exist in subfolders of provided folder")
@click.option("--tag", default="None", help="Tag for downstream pipeline execution")
@click.pass_context
def root(ctx, folder, meta, dry, parentfolder, tag):
    """NGP File uploader"""
    ctx.obj = {}
    handler=Handler()

    #Recursively loop over all folders
    for root, dirs, files in os.walk(folder):
        log.debug("{} {} {}".format(root,dirs,files))
        for f in files:
            try:
                handler.verify_fastq_suffix(os.path.join(root,f))
                handler.verify_fastq_contents(os.path.join(root,f))
                handler.gen_metadata(os.path.join(root,f), tag)
            except Exception as e:
                log.debug("{} is not a valid upload file".format(f))
