"""

"""

from smug import version, log, WD, TIMESTAMP
from smug.handler import Handler

#!/usr/bin/env python

import click

@click.command()
@click.version_option(version)
@click.argument('folder', type=click.Path(exists=True))
@click.option("--meta", type=click.Path(exists=True), default="/", help="Override the autogenerated metadata with your own")
@click.option("--dry", is_flag=True, default=False, help="Does not execute anything")
@click.option("--parentfolder", is_flag=True, default=False, help="Samples exist in subfolders of provided folder")
@click.option("--tag", default="None", help="Tag for downstream pipeline execution")
@click.pass_context
def root(ctx, folder, meta, dry, parentfolder, tag):
    """NGP File uploader"""
    ctx.obj = {}

    handler=Handler()
    handler.verify_fastq(folder)
    handler.gen_metadata(folder, tag)
    #Add logger
    #generate metadata file
    #check that all files contain fasta
    #add folder function
    #add folder of folder function
